### ISSUE TITLE
[BUG] Upgrade from 0b2da44 to current results in Server Error (500)

### ISSUE THREAD

**Issue by querex007** [TheSpaghettiDetective/obico-server#1011]
**Describe the bug**
Upgrade from 0b2da44 to current results in Server Error (500)

**To Reproduce**
1. Set up ennvironment with release 0b2da44
2. Perform upgrade as documentation says: git checkout release && git pull && docker compose up --build -d
(https://www.obico.io/docs/server-guides/ops/)
3. Opening web GUI on port 3334 results into a "Server Error (500)"

**Hardware**
Intel NUC 10th gen
Proxmox 8.2.4
Ubuntu 24.04 LTS VM with docker 27.1.1, build 6312585 installed
Obico server running inside docker, without GPU

**Log files in attachment**
[_obico-server-ml_api-1_logs.txt](https://github.com/user-attachments/files/16568878/_obico-server-ml_api-1_logs.txt)
[_obico-server-web-1_logs.txt](https://github.com/user-attachments/files/16568879/_obico-server-web-1_logs.txt)

**Comment by appleimperio** [comment]
Try this

````
cd obico-server && docker compose run web ./manage.py site --add ip of the Proxmox VM
````

There is more info on the Django server configuration https://www.obico.io/docs/server-guides/configure/

**Comment by querex007** [comment]
@appleimperio that fixed the issue!
Many thanks.
Will close as resolved.
