### ISSUE TITLE
What are the minimum system requirements for using obico_server?

### ISSUE THREAD

**Issue by ealin1994** [TheSpaghettiDetective/obico-server#1047]
In the configuration notes, it is mentioned that the minimum requirement is a 4th generation CPU, but no specific CPU models are given. Does this refer to 4th generation CPUs for desktops or laptops? For example, can an i3 4010U meet the capability of monitoring two printers? Can it function properly with only integrated graphics?

**Comment by kennethjiang** [comment]
Please go to our discord server to get help like this. github issues are reserved for bugs.
