### ISSUE TITLE
[Question] How can I set up Obico on Synology DSM?

### ISSUE THREAD

**Issue by Monniasza** [TheSpaghettiDetective/obico-server#1051]
Hi. I've been trying to install Obico two ways:
* using the Docker. I haven't found any good entrypoint and there's no reference to whaat endpoint is good. I've tried three entrypoints:
  * python3, which doesn't start the server up at all
  * python /app/manage.py runserver 0.0.0.0:3334, which creates a service which always returns HTTP 500 on any request
  * sh -c 'python manage.py migrate && python manage.py collectstatic -v 2 --noinput && daphne -b 0.0.0.0 -p 3334 config.routing:application', which crashes the container shortly after startup
* with Git, which is not available on DSM

Is there any other way that I could try?

**Comment by kennethjiang** [comment]
Our github issues are reserved for confirmed code issue and feature requests only. You will get help a lot faster by joining in the conversation on our discord server: https://obico.io/discord/.
