### ISSUE TITLE
Email templates don't refer to private server

### ISSUE THREAD

**Issue by marcelrv** [TheSpaghettiDetective/obico-server#127]
The email templates in  `/web/app/templates/email/`
have hardcoded link to `https://app.thespaghettidetective.com/prints/` instead of using something like `site.build_full_url('/prints/')`

This means that the link will bring you to the wrong print

**Comment by marcelrv** [comment]
Also seems like the new templates on private server complain about the low on detective hours

` You are running low on Detective Hours. Get more if you want The Detective to keep watching your prints.`

**Comment by kennethjiang** [comment]
I can totally see how that happens! Need to think a bit more about how Detective Hours should be dealt with on private servers...

**Comment by kennethjiang** [comment]
Already fixed.
