### ISSUE TITLE
Caddy 2 reverse proxy support?

### ISSUE THREAD

**Issue by thegillimonster** [TheSpaghettiDetective/obico-server#250]
I see there is Traefik and NGinx support. I was curious if anyone has made the webserver work with Caddy reverse proxy? I have tried the normal Caddyfile stuff but I can only make it spit out a white screen at https://spaghetti.my.domain.

**Comment by kennethjiang** [comment]
None of us on the dev team is familiar with Caddy. Want to write up something and send it in as a PR? :)

**Comment by kennethjiang** [comment]
Reverse proxy is outside the scope of this project. But you are more than welcome to figure it out and write a guide for it and contribute to the Obico community: https://www.obico.io/docs/developer-guides/contribute/
