### ISSUE TITLE
Suggestion: Upload timelapse directly from octoprint

### ISSUE THREAD

**Issue by alexbaucom17** [TheSpaghettiDetective/obico-server#270]
I would be happy to upload full timelapses for training, but it's a bit of a hassle to download from octoprint to my PC and then upload to TSD. If there was an easy way to upload (potentially even auto-upload, obviously toggleable) directly from OctoPrint, I would be much more likely to use it.

**Comment by kennethjiang** [comment]
Yes have been thinking about this for a while now. Getting more training data is not our bottleneck right now but we will most likely get a chance to do this over the next several months.
