### ISSUE TITLE
[BUG] No webcam or Timelapse when accessing private server from external ip.

### ISSUE THREAD

**Issue by tenumars** [TheSpaghettiDetective/obico-server#639]
**Describe the bug**
When opening server IP address using public ip and port 3334, the whole server loads but not the webcam or Timelapses. But, when I am on my home network and run the external ip, it works. I don't know what it is?

**To Reproduce**
1. Port forward server
2. Open server using external ip not on local network
3. No webcam loads

**Screenshots**
![image](https://user-images.githubusercontent.com/98669318/168284407-02940251-a072-4255-b281-6fc3da9e013e.jpeg)
![image](https://user-images.githubusercontent.com/98669318/168284434-040369bf-09b0-40fd-8cad-8e3d5342afe6.jpeg)

**Hosting environment (please complete the following information):**
 - OS: any, web browser
 - Version latest
 - Hardware 64 core windows server with 96gb ram, 50mbps upload speed

**Additional context**
Thanks for the help!

**Comment by kennethjiang** [comment]
This is likely caused by your server setup/configuration. Please go to https://www.obico.io/discord/ to seek help. A github issue needs to be reproducible by Obico developers, which is not the case for this issue.
