### ISSUE TITLE
[Tech Debt] DRY error handling for consumers

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/obico-server#685]
We have repeated error handling in the `consumer.py` such as this https://github.com/TheSpaghettiDetective/obico-server/blob/0614f7ce18b97a3c34e07f777961909654bc9dc9/backend/api/consumers.py#L504

It'll be great if we can create a decorator to DRY this. Also we need to make sure all consumers methods that are not automatically handled by sentry (I think `connect` is automatically handled but I'm not sure) should have this decorator.

**Comment by encetamasb** [comment]
Fixed in #686
