### ISSUE TITLE
[Enable use of Obico with Octolapse]  can't use custom image preferencs on octolapse and use obico at the same time

### ISSUE THREAD

**Issue by 999Chilly** [TheSpaghettiDetective/obico-server#700]
I love how I can use Obico away from home. However, I wish I could also use octolapse at the same time to get cool print timelapses. Octolapse looks kind of dull without the custom image preferences tab that allows you to change settings like brightness, contrast, exposure, focus, zoom, etc. If you guys would be able to communicate with the devs of octolapse and figure out a way to make them both work at the same time, that would be great. Thanks for reading and I hope you consider my suggestion!

Here is the link to the post saying they don't work together (they call it spaghetti detective which is now obviously called obico): 
https://github.com/FormerLurker/Octolapse/wiki/V0.4---Enabling-Camera-Controls

**Comment by kennethjiang** [comment]
The link is out of date. Now Obico is fully compatible with octolapse. Feel free to reopen this issue if you run into any problems.
