### ISSUE TITLE
USB camera rotation / settings

### ISSUE THREAD

**Issue by OwendB1** [TheSpaghettiDetective/obico-server#728]
**Is your feature request related to a problem? Please describe.**
I have been trying for 2 days to use MJPEG streamer and/or FFMPEG to try and rotate my camera 180 degrees because physically rotating the camera is not possible. I'm trying to accomplish this on a USB camera (C270) with FLuidd and Mainsail.

**Describe the solution you'd like**
It would be ideal if Obico allowed for a postprocessing setting that rotates the camera 180 or allows it to flip it when using Fluidd

**Describe alternatives you've considered**
A clear and concise description of how to achieve rotating a USB camera using MainsailOS.

**Comment by kennethjiang** [comment]
This option is there already: https://obico.io/docs/user-guides/moonraker-obico/config/#webcam-section

Have you tried that?

**Comment by OwendB1** [comment]
I could not find these settings when googling it for some reason. Turning on flip vertically and horizontally has resolved this for me. Thanks!
