### ISSUE TITLE
Black screen after update

### ISSUE THREAD

**Issue by borislavstefanov** [TheSpaghettiDetective/obico-server#781]
after the update it is constantly sitting on a black screen and buffering, it was tested through a phone and through a web browser and it shows the same thing - a black screen. the update was on a кlipper/voron 2.4 mainsail

![image](https://user-images.githubusercontent.com/6666322/229621736-6dacab49-3490-4086-95ee-c61209675817.png)

**Comment by kennethjiang** [comment]
Closing this issue as we are addressing this in your email and your discord ticket.
