### ISSUE TITLE
[BUG?] Mails from Obico sent to Apple are not showing camera snapshot directly

### ISSUE THREAD

**Issue by nicktodorov** [TheSpaghettiDetective/obico-server#786]
**Describe the bug**
For some reason, notification mails from Obico self hosted server do not show the camera snapshot. 
There is message "Your network preferences prevent content from loading privately.". But the problem is, that in order to make this work as supposed, I need to turn off completely Private relay feature, which I do not want for obvious reasons. 
Since this is the only email that has this issue (even span loads correctly), there should be something specific on how Obico emails are working.
Apologies if this is a setting I have missed and not a bug, but I could not find anything on this topic specific to Obico.

**To Reproduce**
1. Setup Obico self hosted server
2. Configure email notifications
3. Open notification email on an Apple device. It doesn't matter what mail client or device is used, if there is Private Relay (hiding your IP address for email tracking), the problem is reproducible.

**Screenshots**

**Hosting environment (please complete the following information):**
 - OS: iOS, Mac OS
 - Version: 16.4.1, Ventura 13.3.1
 - Hardware: Mac, iPhone, iPad

**Comment by nicktodorov** [comment]
Where do I have to set this SSL? In docker, in Django or the ngrok?

**Comment by kennethjiang** [comment]
@nicktodorov Please refer to other sys admin resources for how you can set up SSL.

I'm closing this issue as managing SSL is outside the scope of the Obico server. If there is reason to believe this is really a bug, please come back and reopen it.
