### ISSUE TITLE
[Feature] Camera-streamer/rtsp webcam compatability added to obico-server

### ISSUE THREAD

**Issue by kaibsora** [TheSpaghettiDetective/obico-server#800]
**Is your feature request related to a problem? Please describe.**

Using moonraker-crowsnest camera-streamer does not work with obico. It uses rtsp.

**Describe the solution you'd like**

streaming to work with rtsp outputs

**Describe alternatives you've considered**

none

**Additional context**

**Comment by kennethjiang** [comment]
moonraker-obico 1.4.0 works with rtsp. https://discord.com/channels/614543405724205137/661368008781987841/1113083710456213604
