### ISSUE TITLE
Web with obico-server didn't capture the stream

### ISSUE THREAD

**Issue by YaphetS1** [TheSpaghettiDetective/obico-server#837]
Hi there!
I had write an issue in moonraker-obico, but I think the problem is here. Help me pls 🥲 

To avoid duplication, I will attach a link to the problem [#83](https://github.com/TheSpaghettiDetective/moonraker-obico/issues/83)

**Comment by YaphetS1** [comment]
Today I'm tried to change resolution of camera capture and change browser to chrome - it's get me more information for debug. But not clarify the situation... Camera resolution reduce to 1280x720 from native 2592x1944. And again the clipper caught the stream, but the obiko did not

**Comment by YaphetS1** [comment]
In obico-server i got this in console
<img width="2423" alt="capture chrome console" src="https://github.com/TheSpaghettiDetective/obico-server/assets/24227561/663f9cc4-d653-46f6-9d4d-2b62f08e5345">

**Comment by kennethjiang** [comment]
in our work flow, github issues are opened only for confirmed bugs or feature requests. Again what you described here looks more like a configuration issue. Please come to our discord channel to get prompt help.
