### ISSUE TITLE
Add licensing information for the neural network

### ISSUE THREAD

**Issue by antirez** [TheSpaghettiDetective/obico-server#838]
Hello, I'm planning to use the ONNX neural network from the server in my own project, just for inference without using any Obico Server code. I wonder what is the license of the neural network itself, I mean the already trained set of weights, not the code to replicate it. Thanks.

**Comment by kennethjiang** [comment]
No. The license for the AI model is the same as the server itself.

**Comment by antirez** [comment]
For me it is perfect. Just it may not be obvious since the license of the server is usually a code license that does not cover very well the usage of a set of weights. Thanks.
