### ISSUE TITLE
Add a button to let use share their time-lapse publicly in Spaghetti Gallery

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/obico-server#92]

**Comment by ajdavids** [comment]
Would this work like in octoprint, with a sharing/not sharing slider?

**Comment by kennethjiang** [comment]
I think it's probably more just like a button or menu item that says "Share it in Spaghetti Gallery". Since it'll be tricky to "unshare", so I don't think we want to make it a toggle.
