### ISSUE TITLE
[BUG] o/authorize is not available

### ISSUE THREAD

**Issue by mthqwork** [TheSpaghettiDetective/obico-server#933]
**Describe the bug**
I am running obico using docker. When I try to login from OrcaSlicer, it ends up in "Not found". 
It tries to load https://myhost.xyz/o/authorize which is 404.
Traced it down in obico-server-web, log says: 
django.request WARNING Not Found: /o/authorize.

**To Reproduce**
1. Install obico in docker
2. Try to login from OrcaSlicer

**Screenshots**

**Hosting environment (please complete the following information):**
Debian 12, latest docker, latest docker image.

**Additional context**
-
![Screenshot_2024-04-24_00-10-23](https://github.com/TheSpaghettiDetective/obico-server/assets/19063751/d3d4a102-89bd-4017-85fc-edcd0f580f09)
![Screenshot_2024-04-24_00-10-39](https://github.com/TheSpaghettiDetective/obico-server/assets/19063751/fca7fdcd-2418-4615-9b65-b938a5647fee)

**Comment by kennethjiang** [comment]
Please use the `pre-release`: https://discord.com/channels/614543405724205137/661368008781987841/1229143203207319583
