### ISSUE TITLE
[BUG] Recommendation to remove a default secret key

### ISSUE THREAD

**Issue by FHantke** [TheSpaghettiDetective/obico-server#990]
Hello Obico-Server developers,

We are a cybersecurity research group from the CISPA Helmholtz Center for Information Security and Ca’ Foscari University of Venice. We recently conducted an analysis of the session management in web applications on GitHub as part of our research. We have discovered a security flaw in your code that we believe requires your attention.

**Description:**

With our analysis, we have identified that your application is[ using a hard-coded secret key if the `DJANGO_SECRET_KEY` environment variable is not set](https://github.com/TheSpaghettiDetective/obico-server/blob/release/backend/config/settings.py#L30). This secret key is used in several parts of the application, for example, to [calculate and verify the hash for private media files](https://github.com/TheSpaghettiDetective/obico-server/blob/471c0364c7c823194bc9c5c2b13e76aa1ebad6b9/backend/lib/url_signing.py#L19) as access protection. We assume that someone knowing the hard-coded secret key could bypass your media hash access control mechanism.

**Recommendation for Mitigation:**

We recommend two things. First, do not use a default fallback key for the secret key. A user will see from the error message that they need to set a secret key. You already [documented how to configure the secret key](https://www.obico.io/docs/server-guides/configure/#re-generate-django_secret_key), put this reference also in [the installation guide](https://www.obico.io/docs/server-guides/install/). Second, if you want to keep the hash protected access control for file (assumably, to allow sharing files with other who don’t have an account?), we would recommend adding some additional secret to the HMAC, for example, the user’s password hash.

We hope this notification helps improve your security.

In addition to addressing this issue, we are interested in understanding how this flaw was introduced in the code or why it has remained unchanged. This information can provide valuable insights into common security pitfalls and help us all improve security practices in the future. Could you share any background on this aspect? We would greatly appreciate your input on this matter. Thank you!

Should you have further questions or comments on this, feel free to answer this thread or reach out to florian.hantke@cispa.de.

Kind regards,
Florian Hantke

**Comment by kennethjiang** [comment]
Obico-server is configured as a local-only server by default. We have made it very clear to our users that they are responsible for the security of their server (as well as their overall setup such as reverse proxy), especially if they choose to expose their server to the internet.

The reason why we chose to not add this part to the getting started guide is because if we choose to add this one, we will need to add a bunch of other things of equal or higher importance to the guide, defeating the purpose as "a guide to get you started".
