### ISSUE TITLE
[BUG] webcam only works when on local lan, and Timelapse doesn't work

### ISSUE THREAD

**Issue by billkenney** [TheSpaghettiDetective/obico-server#996]
**Note**
I've deleted everything on my server and printer multiple times, and reinstalled, but this issue persists. The camera only works when I'm connected to my LAN, and the timelapse doesn't work (moonraker-timelapse does work)

**Describe the bug**
Camera doesn't work outside of the LAN. Timelapse doesn't work. 

**To Reproduce**

1. Install the server via docker compose, configure the domain, configure the user

2. Install obico on the printer. 

3. Link the server to the printer

4. Edit the cfg file. I've tried using 127.0.0.1, localhost, the local ip address of the printer for the stream/snapshot url, and I tried not including a stream or snapshot url at all. Nothing works. If I don't include the url, the image doesn't even work on my local network. 

**Hosting environment (please complete the following information):**
I'm using the latest iOS, or a web app, the behavior is the same

My server is running Ubuntu 22.04 and I update to the latest version of the server every time I try again

My printer is running Bookworm with the latest klipper, moonraker, fluidd, Obico, etc

**Additional context**
For some reason, moonraker-timelapse wouldn't save my timelapses for a long time, but obico did. Now Obico doesn't. I don't really care about timelapse outside the LAN, but I do care about seeing if my print is okay

**Comment by kennethjiang** [comment]
This is more likely than not an issue related django site configuration, or your reverse proxy set up, or something else. 

Github issues are reserved for code issues only, mainly bugs and feature requests. Please bring this issue to our discord server https://obico.io/discord/ until we confirm this is code issue.
